### ISSUE TITLE
Feature Suggestion: handle github enterprise

### ISSUE THREAD

**Issue by s-kocher** [erichbehrens/pull-request-monitor#26]
Hello,
thanks for this extension :)

It will be nice to allow enterprise users with a dedicated instance of github enterprise to use it too, I don't see any setting to declare the url of a specific github server.

**Comment by AngefloMusic** [comment]
Have added the support in #27 ! :)

**Comment by erichbehrens** [comment]
@AngefloMusic thanks for your contribution. The update is published to the marketplace!
